services:

  # Lucee Application for example
  # ---------------

  frontend:
    image: quetwo/restendpointfails:LATEST
    build:
      context: frontend/
    volumes:
      - ./frontend/webroot:/var/www
    environment:
      - LUCEE_ADMIN_PASSWORD=admin-password
    ports:
      - 8888:8888